-- 1. Arreglar la columna sell_price (quitar la autogeneración)
ALTER TABLE price_catalog DROP COLUMN IF EXISTS sell_price;
ALTER TABLE price_catalog ADD COLUMN sell_price numeric DEFAULT 0;

-- 2. Asegurarse de que las columnas de mercado existen (por si acaso)
ALTER TABLE price_catalog ADD COLUMN IF NOT EXISTS market_price numeric;
ALTER TABLE price_catalog ADD COLUMN IF NOT EXISTS market_price_updated_at timestamptz;

-- 3. Quitar las restricciones de las unidades para que acepte "each", "linear_ft", etc sin problemas
ALTER TABLE price_catalog DROP CONSTRAINT IF EXISTS price_catalog_unit_type_check;

-- 4. Refrescar el caché de Supabase para que ya no dé el error de "schema cache"
NOTIFY pgrst, 'reload schema';

-- 5. Limpiar los precios viejos para evitar duplicados
DELETE FROM price_catalog WHERE id IS NOT NULL;

-- 6. Insertar la nueva TABLA OFICIAL 2026
INSERT INTO price_catalog (category, item_name, unit_type, base_cost, margin_pct, sell_price) VALUES
('roofing', 'ASPHALT ROOF', 'sq', 0, 0, 350),
('roofing', 'ASPHALT ROOF (INSURANCE JOBS)', 'sq', 0, 0, 400),
('roofing', 'METAL ROOF (ANY COLOR)', 'sq', 0, 0, 1000),
('roofing', 'TPO ROOF', 'sq', 0, 0, 1200),
('roofing', 'PLYWOOD REPLACEMENT (ROOF & EXTERIOR WALLS)', 'each', 0, 0, 90),
('roofing', 'SKYLIGHT REPLACEMENT', 'each', 0, 0, 1950),
('general', 'CHIMNEY FLASHING REPLACEMENT (STANDARD)', 'each', 0, 0, 1500),
('gutters', 'GUTTERS & DOWNSPOUTS (5” / 6”)', 'linear_ft', 0, 0, 15),
('gutters', 'GUTTER GUARD', 'linear_ft', 0, 0, 8),
('siding', 'VINYL SOFFIT', 'linear_ft', 0, 0, 18),
('siding', 'METAL WRAPPED FASCIA', 'linear_ft', 0, 0, 18),
('deck', 'VINYL PORCH', 'linear_ft', 0, 0, 35),
('siding', 'VINYL SIDING – HORIZONTAL', 'sq', 0, 0, 580),
('siding', 'VINYL SIDING – VERTICAL', 'sq', 0, 0, 850),
('siding', 'HARDIE BOARD (FIBER CEMENT)', 'sq', 0, 0, 1500),
('siding', 'WOOD SIDING (RECOMMENDED)', 'sq', 0, 0, 2000),
('windows', 'VINYL WHITE', 'each', 0, 0, 400),
('windows', 'VINYL SAND', 'each', 0, 0, 750),
('windows', 'VINYL BLACK', 'each', 0, 0, 950),
('windows', 'BASEMENT WINDOW – WHITE', 'each', 0, 0, 400),
('windows', 'BASEMENT WINDOW – OTHER COLOR', 'each', 0, 0, 650),
('windows', 'BASEMENT EGRESS WINDOW – ALL INCLUDED', 'each', 0, 0, 5800),
('windows', 'INTERIOR DOOR', 'each', 0, 0, 850),
('windows', 'EXTERIOR DOOR 36” × 80”', 'each', 0, 0, 2900),
('windows', 'EXTERIOR STORM DOOR', 'each', 0, 0, 950),
('windows', 'DOUBLE EXTERIOR DOOR 70–72” × 80”', 'each', 0, 0, 3500),
('windows', 'SLIDING GLASS DOOR', 'each', 0, 0, 3200),
('windows', 'NEW OPENING (ANY DOOR)', 'each', 0, 0, 3900),
('windows', 'GARAGE DOOR METAL WRAP (1–2 CAR)', 'each', 0, 0, 250),
('windows', 'door y windows METAL WRAP', 'each', 0, 0, 150),
('windows', '70–72” × 80” METAL WRAP', 'each', 0, 0, 180),
('general', '1-CAR GARAGE DOOR', 'each', 0, 0, 2950),
('general', '2-CAR GARAGE DOOR', 'each', 0, 0, 3800),
('general', 'CUSTOM / BLACK / DESIGNER GARAGE DOOR', 'each', 0, 0, 5500),
('general', 'OPENER INSTALL ONLY', 'each', 0, 0, 1250),
('deck', 'TREATED WOOD DECK + RAILS + STAIRS', 'linear_ft', 0, 0, 35),
('deck', 'COMPOSITE DECK + RAILS + STAIRS', 'linear_ft', 0, 0, 75),
('deck', 'WOOD DECK + VINYL/ALUMINUM RAILS', 'linear_ft', 0, 0, 60),
('deck', 'PORCH FRAMING', 'linear_ft', 0, 0, 55),
('deck', 'PATIO FRAMING', 'linear_ft', 0, 0, 50),
('deck', 'WOOD PERGOLA (STANDARD)', 'sqft', 0, 0, 50),
('deck', 'COVERED PERGOLA', 'sqft', 0, 0, 65),
('deck', 'PERGOLA WITH METAL ROOF', 'sqft', 0, 0, 75),
('deck', 'PERGOLA WITH POLYCARBONATE PANELS', 'sqft', 0, 0, 85),
('general', '200 AMP PANEL', 'each', 0, 0, 4800),
('general', 'NEW CIRCUIT (BED / BATH)', 'each', 0, 0, 1500),
('general', 'DEDICATED LINE (DRYER / RANGE)', 'each', 0, 0, 950),
('general', 'LIGHT FIXTURE INSTALL', 'each', 0, 0, 200),
('general', 'CEILING FAN INSTALL', 'each', 0, 0, 300),
('general', 'OUTLET / SWITCH INSTALL', 'each', 0, 0, 90),
('general', 'FULL KITCHEN REMODEL', 'each', 0, 0, 25000),
('general', 'CABINET INSTALL', 'unit', 0, 0, 250),
('general', 'GRANITE / QUARTZ COUNTERTOP', 'linear_ft', 0, 0, 85),
('general', 'BACKSPLASH INSTALL', 'sqft', 0, 0, 12),
('general', 'DISHWASHER INSTALL', 'each', 0, 0, 250),
('general', 'OVEN INSTALL', 'each', 0, 0, 250),
('general', 'MICROWAVE INSTALL', 'each', 0, 0, 200),
('general', 'FAUCET INSTALL', 'each', 0, 0, 180),
('general', 'GARBAGE DISPOSAL INSTALL', 'each', 0, 0, 250),
('general', 'FULL BATH – TILE SHOWER WALLS & FLOOR + BATH FLOOR (100% FINISHED)', 'each', 0, 0, 15500),
('general', 'PLASTIC WALL SYSTEM + GLASS DOOR (100% FINISHED)', 'each', 0, 0, 12900),
('general', 'FULL BATH – LABOR ONLY (CUSTOMER PROVIDES MATERIALS)', 'each', 0, 0, 8900),
('general', 'SHOWER ONLY – PLASTIC WALLS + GLASS DOOR', 'each', 0, 0, 6900),
('general', 'SHOWER ONLY – PLASTIC WALLS (NO GLASS DOOR)', 'each', 0, 0, 5750),
('general', 'CUSTOM SHOWER DOOR (UP TO 60”)', 'each', 0, 0, 2500),
('general', 'STANDARD SHOWER DOOR (UP TO 60”)', 'each', 0, 0, 1850),
('general', 'VANITY INSTALL – SINGLE', 'each', 0, 0, 450),
('general', 'VANITY INSTALL – DOUBLE', 'each', 0, 0, 600),
('general', 'MIRROR INSTALL', 'each', 0, 0, 150),
('general', 'TOILET INSTALL', 'each', 0, 0, 250),
('general', 'FAUCET SET INSTALL', 'each', 0, 0, 180),
('general', 'EXHAUST FAN INSTALL', 'each', 0, 0, 300),
('general', 'INSTALL / REPLACE TOILET', 'each', 0, 0, 450),
('general', 'INSTALL / REPLACE SINK + DRAIN', 'each', 0, 0, 450),
('general', 'INSTALL / REPLACE FAUCET', 'each', 0, 0, 220),
('general', 'GARBAGE DISPOSAL INSTALL', 'each', 0, 0, 280),
('general', 'SHOWER VALVE + TRIM', 'each', 0, 0, 750),
('general', 'BATHTUB INSTALL (STANDARD)', 'each', 0, 0, 1100),
('general', 'SHOWER BASE INSTALL', 'each', 0, 0, 950),
('general', 'NEW WATER LINE (PEX/COPPER)', 'linear_ft', 0, 0, 18),
('general', 'NEW DRAIN LINE (PVC)', 'linear_ft', 0, 0, 22),
('general', 'LAUNDRY HOOKUPS (COMPLETE)', 'each', 0, 0, 750),
('general', 'FULL BATHROUGH-IN', 'each', 0, 0, 1600),
('general', 'WATER HEATER (TANK)', 'each', 0, 0, 1650),
('general', 'TANKLESS WATER HEATER', 'each', 0, 0, 3900),
('general', 'SUMP PUMP + DISCHARGE', 'each', 0, 0, 850),
('general', 'MAIN SEWER REPAIR / REPLACE', 'each', 0, 0, 5000),
('general', 'GAS LINE INSTALL (STANDARD)', 'each', 0, 0, 950),
('general', 'LAMINATE FLOORING', 'sqft', 0, 0, 7),
('general', 'TILE FLOORING', 'sqft', 0, 0, 15),
('general', 'BASEBOARDS', 'linear_ft', 0, 0, 4),
('general', 'CROWN MOLDING', 'linear_ft', 0, 0, 6),
('general', 'PLYWOOD / WOOD REPLACEMENT', 'each', 0, 0, 60),
('general', 'JOIST REPAIR (UP TO 16 FT)', 'each', 0, 0, 300),
('general', 'JOIST REPAIR (OVER 16 FT)', 'each', 0, 0, 380),
('general', 'INTERIOR PAINTING', 'sqft', 0, 0, 4.50),
('general', 'EXTERIOR PAINTING', 'sqft', 0, 0, 5),
('general', 'PAINTING PER ROOM', 'each', 0, 0, 800),
('general', 'PAINTING PER BATHROOM', 'each', 0, 0, 800),
('general', 'PAINTING INTERIOR DOOR', 'each', 0, 0, 350),
('general', 'PAINTING EXTERIOR DOOR', 'each', 0, 0, 750),
('general', 'PAINTING CABINETS', 'each', 0, 0, 300),
('fences', 'PAINTING FENCE', 'linear_ft', 0, 0, 4),
('deck', 'PAINTING DECK ONLY', 'sqft', 0, 0, 4),
('siding', 'EXTERIOR BRICK INSTALL', 'sqft', 0, 0, 28),
('siding', 'FULL BRICK CHIMNEY', 'each', 0, 0, 4500),
('siding', 'STONE INSTALL', 'sqft', 0, 0, 35),
('siding', 'STUCCO FINISH', 'sqft', 0, 0, 22),
('general', 'DRIVEWAY – REMOVE & REPLACE', 'sqft', 0, 0, 18),
('general', 'DRIVEWAY – NEW ONLY', 'sqft', 0, 0, 16),
('general', 'CONCRETE STEPS', 'each', 0, 0, 350),
('general', 'PATIO / PORCH (4”)', 'sqft', 0, 0, 14),
('general', 'GARAGE SLAB (6”)', 'sqft', 0, 0, 15),
('general', 'FOOTING / FOUNDATION', 'linear_ft', 0, 0, 20),
('general', 'BLOCK WORK', 'sqft', 0, 0, 18),
('general', 'SIDEWALKS (4”)', 'sqft', 0, 0, 12),
('general', 'ASPHALT DRIVEWAY (3.5”)', 'sqft', 0, 0, 15),
('fences', 'CHAIN LINK – GALVANIZED (4 FT)', 'linear_ft', 0, 0, 30),
('fences', 'CHAIN LINK – BLACK (4 FT)', 'linear_ft', 0, 0, 30),
('fences', 'WOOD FENCE – DOG EAR (6 FT)', 'linear_ft', 0, 0, 35),
('fences', 'HORSE FENCE – WOOD (4 FT)', 'linear_ft', 0, 0, 35),
('fences', 'BLACK ALUMINUM (4 FT)', 'linear_ft', 0, 0, 45),
('fences', 'WHITE VINYL (6 FT)', 'linear_ft', 0, 0, 60),
('fences', 'SAND VINYL (6 FT)', 'linear_ft', 0, 0, 70),
('fences', 'GRAY VINYL (6 FT)', 'linear_ft', 0, 0, 75),
('fences', 'FENCE DEMOLITION (UP TO 250 FT)', 'each', 0, 0, 500),
('fences', 'SINGLE GATE', 'each', 0, 0, 250),
('fences', 'DOUBLE GATE', 'each', 0, 0, 400),
('fences', 'EXTRA DRILLING', 'each', 0, 0, 5),
('general', 'HVAC GOODMAN – 2.5T', 'each', 0, 0, 7900),
('general', 'HVAC GOODMAN – 3T', 'each', 0, 0, 8900),
('general', 'HVAC GOODMAN – 4T', 'each', 0, 0, 9900),
('general', 'HVAC GOODMAN – 5T', 'each', 0, 0, 10900),
('general', 'NEW CONSTRUCTION (FULL BUILD)', 'sqft', 0, 0, 190),
('general', 'ADDITION + SIDING + BATHROOM', 'sqft', 0, 0, 190),
('general', 'BRICK ADDITION + BATHROOM', 'sqft', 0, 0, 200),
('general', 'SIDING ADDITION – NO BATH/KITCHEN/PLUMBING', 'sqft', 0, 0, 170);
